version: '3.9'
services:

  fastapi:
    build:
      context: ./fastApi
      dockerfile: Dockerfile
    container_name: fastapi-app
    ports:
      - "8000:8000"
    volumes:
      - ./fastApi:/app:rw

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: npm run dev
    container_name: geoventure-backend-app
    environment:
      - FIREBASE_KEY_JSON_PATH=./key.json
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/app:rw
      - /app/node_modules
      - /app/dist
