version: '3.9'
services:

  fastapi:
    build:
      context: ./fastApi
      dockerfile: Dockerfile
    container_name: fastapi-app
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/app/key.json
    ports:
      - "8000:8000"
    volumes:
      - ./fastApi:/app:rw
      - ./fastApi/key.json:/app/key.json:ro

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: geoventure-backend-app
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/app:rw
      - ./backend/key.json:/app/key.json:ro
      - /app/node_modules
      - /app/dist
    working_dir: /app
