version: '3.9'
services:

  fastapi:
    build:
      context: ./fastApi
      dockerfile: Dockerfile
    container_name: fastapi-app
    ports:
      - "8000:8000"
    volumes:
      - .:/fastApi:ro

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: geoventure-backend-app
    environment:
      - FIREBASE_KEY_JSON_PATH=./key.json
    ports:
      - "3000:3000"