name: Continuous Integration

on:
  push:
    branches:
      - feature/linting-ci
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Unlock npm cache
        run: npm cache verify

      - name: Print npm version
        run: npm --version

      - name: Clean npm cache
        run: npm cache clean --force

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '19.4.0'
          cache: npm

      - name: Install Node.js dependencies
        run: |
          cd ./backend
          npm install
      
      - name: List files in working directory
        run: ls -R
        working-directory: ./backend
        
      - name: Run Node.js lint script
        run: |
          cd ./backend
          npm run lint

      - name: Run Node.js test scripts using Jest
        run: |
          cd ./backend
          npm test
